name: CI

on:
  push:
    branches:
      - master
      - __release-*
  pull_request:

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [12.14.1]
        os: [macos-10.15]
        include:
          - os: macos-10.15
            friendlyName: macOS
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` (`steps.npm-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            vendor/bundle
            .eslintcache
            ~/.electron
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-npm-

      - name: Install and build dependencies
        run: npm install && npm rebuild node-sass
      - name: Lint
        run: npm run lint
      - name: Build production app
        run: NODE_OPTIONS=--max_old_space_size=8192 yarn build:prod
        env:
          KACTUS_OAUTH_CLIENT_ID: ${{ secrets.KACTUS_OAUTH_CLIENT_ID }}
          KACTUS_OAUTH_CLIENT_SECRET: ${{ secrets.KACTUS_OAUTH_CLIENT_SECRET }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM: ${{ secrets.APPLE_TEAM }}
          KACTUSBOT_TOKEN: ${{ secrets.KACTUSBOT_TOKEN }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      # - name: Prepare testing environment
      #   run: yarn test:setup
      # - name: Run unit tests
      #   run: yarn test:unit:cov
      # - name: Run script tests
      #   run: yarn test:script:cov
      # - name: Run integration tests
      #   run: yarn test:integration
      - name: Publish production app
        run: yarn run publish
        if: startsWith(github.ref, 'refs/heads/__release-')
        env:
          KACTUSBOT_TOKEN: ${{ secrets.KACTUSBOT_TOKEN }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
